use master
go
drop database DiemDanhSinhVien
go
create database DiemDanhSinhVien
go
use DiemDanhSinhVien
go

CREATE TABLE [LopHocPhan] (
	[MaLop] NVARCHAR(255) NOT NULL UNIQUE,
	[TenLop] NVARCHAR(255),
	[SiSo] INT,
	[MaGV] NVARCHAR(255),
	[MaMH] NVARCHAR(255),
	[MaPH] NVARCHAR(255),
	PRIMARY KEY([MaLop]),
);
GO
ALTER TABLE [LopHocPhan]
ADD CONSTRAINT CK_SiSo_LHP CHECK (SiSo >= 0);

GO

CREATE TABLE [MonHoc] (
	[MaMH] NVARCHAR(255) NOT NULL UNIQUE,
	[TenMH] NVARCHAR(255),
	[SoTietLyThuyet] INT,
	[SoTietThucHanh] INT,
	[TongSoTiet] INT,
	[SoTinChi] INT,
	PRIMARY KEY([MaMH])
);
GO
ALTER TABLE [MonHoc]
ADD CONSTRAINT CK_SoTietLyThuyet CHECK (SoTietLyThuyet >= 0);
GO
ALTER TABLE [MonHoc]
ADD CONSTRAINT CK_SoTietThucHanh CHECK (SoTietThucHanh >= 0);
GO
ALTER TABLE [MonHoc]
ADD CONSTRAINT CK_TongSoTiet CHECK (TongSoTiet >= 0);
GO
ALTER TABLE [MonHoc]
ADD CONSTRAINT CK_SoTinChi CHECK (SoTinChi >= 0);

GO

CREATE TABLE [GiaoVien] (
	[MaGV] NVARCHAR(255) NOT NULL UNIQUE,
	[HoTenGV] NVARCHAR(255),
	[NamSinh] DATE,
	[GioiTinh] NVARCHAR(255),
	[DiaChi] NVARCHAR(255),
	[MaCM] NVARCHAR(255),
	[MaTD] NVARCHAR(255),
	PRIMARY KEY([MaGV])
);
GO
ALTER TABLE [GiaoVien]
ADD CONSTRAINT CK_GioiTinh_GV CHECK (GioiTinh IN ('Nam', 'Nữ', 'Khác'));
GO
ALTER TABLE [GiaoVien]
ADD CONSTRAINT CK_HoTenGV CHECK (PATINDEX('%[^a-zA-Z-ZÀÁÂÃÈÉÊÌÍÒÓÔÕÙÚĂĐĨŨƠàáâãèéêìíòóôõùúăđĩũơẠ-ỹ]%', HoTenGV) = 0);

GO

CREATE TABLE [SinhVien] (
	[MaSV] NVARCHAR(255) NOT NULL UNIQUE,
	[HoTenSV] NVARCHAR(255),
	[GioiTinh] NVARCHAR(255),
	[NgaySinh] DATE,
	[MaLNC] NVARCHAR(255),
	[SoDienThoai] NVARCHAR(255),
	[Email] NVARCHAR(255),
	[DiaChi] NVARCHAR(255),
	[MaKhoa] NVARCHAR(255),
	[MaNganh] NVARCHAR(255),
	PRIMARY KEY([MaSV])
);
GO
ALTER TABLE [SinhVien]
ADD CONSTRAINT CK_NgaySinh CHECK (
		[NgaySinh] LIKE '[0-3][0-9]/[0-1][0-9]/[1-2][0-9][0-9][0-9]' AND
		ISDATE(STUFF(STUFF([NgaySinh], 3, 0, '-'), 6, 0, '-')) = 1
	);
GO
ALTER TABLE [SinhVien]
ADD CONSTRAINT CK_SoDienThoai CHECK (
        [SoDienThoai] LIKE '[0-9]%' AND 
        LEN([SoDienThoai]) BETWEEN 10 AND 11
    );
GO
ALTER TABLE [SinhVien]
ADD CONSTRAINT CK_Email_SV CHECK (
        [Email] LIKE '%_@__%.__%'
    );
GO
ALTER TABLE [SinhVien]
ADD CONSTRAINT CK_GioiTinh_SV CHECK ([GioiTinh] IN ('Nam', 'Nữ', 'Khác'));

GO

CREATE TABLE [PhongHoc] (
	[MaPH] NVARCHAR(255) NOT NULL UNIQUE,
	[TenPH] NVARCHAR(255),
	[DiaChiPH] NVARCHAR(255),
	PRIMARY KEY([MaPH])
);
GO

CREATE TABLE [DanhSachSinhVien_LopHocPhan] (
	[MaSV] NVARCHAR(255) UNIQUE,
	[MaLop] NVARCHAR(255),
	[MaDD] NVARCHAR(255),
	[SoLanVang] INT,
	[SoLanTre] INT,
	[SoLanCoMat] INT,
	PRIMARY KEY([MaSV], [MaLop], [MaDD])
);
GO
ALTER TABLE [DanhSachSinhVien_LopHocPhan]
ADD CONSTRAINT CK_SoLanVang CHECK ([SoLanVang] >= 0);
GO
ALTER TABLE [DanhSachSinhVien_LopHocPhan]
ADD CONSTRAINT CK_SoLanTre CHECK ([SoLanTre] >= 0);
GO
ALTER TABLE [DanhSachSinhVien_LopHocPhan]
ADD CONSTRAINT CK_SoLanCoMat CHECK ([SoLanCoMat] >= 0);

GO

CREATE TABLE [ChuyenMon] (
	[MaCM] NVARCHAR(255) NOT NULL UNIQUE,
	[TenCM] NVARCHAR(255),
	PRIMARY KEY([MaCM])
);
GO
ALTER TABLE [ChuyenMon]
ADD CONSTRAINT CK_TenCM CHECK (PATINDEX('%[^a-zA-Z-ZÀÁÂÃÈÉÊÌÍÒÓÔÕÙÚĂĐĨŨƠàáâãèéêìíòóôõùúăđĩũơẠ-ỹ]%', [TenCM]) = 0);

GO

CREATE TABLE [TrinhDo] (
	[MaTD] NVARCHAR(255) NOT NULL UNIQUE,
	[TenTD] NVARCHAR(255),
	PRIMARY KEY([MaTD])
);
GO
ALTER TABLE [TrinhDo]
ADD CONSTRAINT CK_TenTD CHECK (PATINDEX('%[^a-zA-Z-ZÀÁÂÃÈÉÊÌÍÒÓÔÕÙÚĂĐĨŨƠàáâãèéêìíòóôõùúăđĩũơẠ-ỹ]%', [TenTD]) = 0);

GO

CREATE TABLE [LopNienChe] (
	[MaLNC] NVARCHAR(255) NOT NULL UNIQUE,
	[TenLNC] NVARCHAR(255),
	[SiSo] INT,
	[MaGV] NVARCHAR(255),
	PRIMARY KEY([MaLNC])
);
GO
ALTER TABLE [LopNienChe]
ADD CONSTRAINT CK_SiSo_LNC CHECK ([SiSo] >= 0);

GO

CREATE TABLE [NguoiDung] (
	[MaND] NVARCHAR(255) NOT NULL UNIQUE,
	[Email] NVARCHAR(255),
	[MatKhau] NVARCHAR(255),
	PRIMARY KEY([MaND])
);
GO
ALTER TABLE [NguoiDung]
ADD CONSTRAINT CK_Email_ND CHECK (
        [Email] LIKE '%_@__%.__%'
    );
GO
ALTER TABLE [NguoiDung]
ADD CONSTRAINT CK_Password_Valid CHECK (
		LEN([MatKhau]) >= 8 AND
		[MatKhau] LIKE '%[A-Z]%' AND
		[MatKhau] LIKE '%[a-z]%' AND
		[MatKhau] LIKE '%[0-9]%' AND
		[MatKhau] LIKE '%[!@#$%^&*(),.?":{}|<>]'
	);

GO

CREATE TABLE [NguoiDung_PhanQuyen] (
	[MaND] NVARCHAR(255) NOT NULL UNIQUE,
	[MaPQ] NVARCHAR(255),
	PRIMARY KEY([MaND]),

);
GO

CREATE TABLE [PhanQuyen] (
	[MaPQ] NVARCHAR(255) NOT NULL UNIQUE,
	[TenNhomQuyen] NVARCHAR(255),
	PRIMARY KEY([MaPQ])
);
GO
ALTER TABLE [PhanQuyen]
ADD CONSTRAINT CK_TenNhomQuyen CHECK (PATINDEX('%[^a-zA-Z-ZÀÁÂÃÈÉÊÌÍÒÓÔÕÙÚĂĐĨŨƠàáâãèéêìíòóôõùúăđĩũơẠ-ỹ]%', [TenNhomQuyen]) = 0);

GO

CREATE TABLE [ChiTietPhanQuyen] (
	[MaCTPQ] NVARCHAR(255) NOT NULL UNIQUE,
	[QuyenDuocCapPhep] NVARCHAR(255),
	[KiemTraHanhDong] INT,
	[MaPQ] NVARCHAR(255),
	PRIMARY KEY([MaCTPQ])
);
GO
ALTER TABLE [ChiTietPhanQuyen]
ADD CONSTRAINT CK_KiemTraHanhDong CHECK ([KiemTraHanhDong] IN (1, 0));

GO

CREATE TABLE [BangDiemDanh] (
	[MaDD] NVARCHAR(255) NOT NULL UNIQUE,
	[NgayDD] DATE,
	[LanDD] INT,
	[TrangThaiDD] INT,
	PRIMARY KEY([MaDD])
);
GO
ALTER TABLE [BangDiemDanh]
ADD CONSTRAINT CK_LanDD CHECK ([LanDD] >= 0);
GO
ALTER TABLE [BangDiemDanh]
ADD CONSTRAINT CK_TrangThaiDD CHECK ([TrangThaiDD] IN (1, 0));

GO

CREATE TABLE [TietHoc] (
	[MaTH] NVARCHAR(255) NOT NULL UNIQUE,
	[TenTH] NVARCHAR(255),
	[GioBD] TIME,
	[GioKT] TIME,
	PRIMARY KEY([MaTH])
);
GO

CREATE TABLE [ThoiGianHoc] (
	[MaTGH] NVARCHAR(255) NOT NULL UNIQUE,
	[SoLuongNgayHoc] INT,
	[NgayBD] DATE,
	[NgayKT] DATE,
	PRIMARY KEY([MaTGH])
);
GO
ALTER TABLE [ThoiGianHoc]
ADD CONSTRAINT CK_NgayBD_NgayKT CHECK ([NgayBD] < [NgayKT]);

GO

CREATE TABLE [NgayHoc] (
	[MaNH] NVARCHAR(255) NOT NULL UNIQUE,
	[Ngay] DATE,
	[Thu] INT,
	PRIMARY KEY([MaNH])
);
GO
ALTER TABLE [NgayHoc]
ADD CONSTRAINT CK_Thu CHECK ([Thu] IN (2, 3, 4, 5, 6, 7));

GO

CREATE TABLE [ChiTietNgayHoc] (
	[MaNH] NVARCHAR(255) UNIQUE,
	[MaTH] NVARCHAR(255),
	[MaLop] NVARCHAR(255),
	PRIMARY KEY([MaNH], [MaTH], [MaLop])
);
GO

CREATE TABLE [ChiTietTGH] (
	[MaTGH] NVARCHAR(255) UNIQUE,
	[MaLop] NVARCHAR(255),
	PRIMARY KEY([MaTGH], [MaLop])
);
GO

ALTER TABLE [LopHocPhan]
ADD FOREIGN KEY([MaMH]) REFERENCES [MonHoc]([MaMH])
ON UPDATE NO ACTION ON DELETE CASCADE;
GO
ALTER TABLE [LopHocPhan]
ADD FOREIGN KEY([MaGV]) REFERENCES [GiaoVien]([MaGV])
ON UPDATE NO ACTION ON DELETE NO ACTION;
GO
ALTER TABLE [DanhSachSinhVien_LopHocPhan]
ADD FOREIGN KEY([MaLop]) REFERENCES [LopHocPhan]([MaLop])
ON UPDATE NO ACTION ON DELETE CASCADE;
GO
ALTER TABLE [DanhSachSinhVien_LopHocPhan]
ADD FOREIGN KEY([MaSV]) REFERENCES [SinhVien]([MaSV])
ON UPDATE NO ACTION ON DELETE CASCADE;
GO
ALTER TABLE [GiaoVien]
ADD FOREIGN KEY([MaTD]) REFERENCES [TrinhDo]([MaTD])
ON UPDATE NO ACTION ON DELETE CASCADE;
GO
ALTER TABLE [LopHocPhan]
ADD FOREIGN KEY([MaPH]) REFERENCES [PhongHoc]([MaPH])
ON UPDATE NO ACTION ON DELETE CASCADE;
GO
ALTER TABLE [GiaoVien]
ADD FOREIGN KEY([MaCM]) REFERENCES [ChuyenMon]([MaCM])
ON UPDATE NO ACTION ON DELETE CASCADE;
GO
ALTER TABLE [SinhVien]
ADD FOREIGN KEY([MaLNC]) REFERENCES [LopNienChe]([MaLNC])
ON UPDATE NO ACTION ON DELETE CASCADE;
GO
ALTER TABLE [LopNienChe]
ADD FOREIGN KEY([MaGV]) REFERENCES [GiaoVien]([MaGV])
ON UPDATE NO ACTION ON DELETE CASCADE;
GO
ALTER TABLE [NguoiDung_PhanQuyen]
ADD FOREIGN KEY([MaND]) REFERENCES [NguoiDung]([MaND])
ON UPDATE NO ACTION ON DELETE CASCADE;
GO
ALTER TABLE [NguoiDung_PhanQuyen]
ADD FOREIGN KEY([MaPQ]) REFERENCES [PhanQuyen]([MaPQ])
ON UPDATE NO ACTION ON DELETE CASCADE;
GO
ALTER TABLE [ChiTietPhanQuyen]
ADD FOREIGN KEY([MaCTPQ]) REFERENCES [PhanQuyen]([MaPQ])
ON UPDATE NO ACTION ON DELETE CASCADE;
GO
ALTER TABLE [DanhSachSinhVien_LopHocPhan]
ADD FOREIGN KEY([MaDD]) REFERENCES [BangDiemDanh]([MaDD])
ON UPDATE NO ACTION ON DELETE CASCADE;
GO
ALTER TABLE [ChiTietNgayHoc]
ADD FOREIGN KEY([MaNH]) REFERENCES [NgayHoc]([MaNH])
ON UPDATE NO ACTION ON DELETE CASCADE;
GO
ALTER TABLE [ChiTietNgayHoc]
ADD FOREIGN KEY([MaTH]) REFERENCES [TietHoc]([MaTH])
ON UPDATE NO ACTION ON DELETE CASCADE;
GO
ALTER TABLE [ChiTietTGH]
ADD FOREIGN KEY([MaTGH]) REFERENCES [ThoiGianHoc]([MaTGH])
ON UPDATE NO ACTION ON DELETE CASCADE;
GO
ALTER TABLE [ChiTietNgayHoc]
ADD FOREIGN KEY([MaLop]) REFERENCES [LopHocPhan]([MaLop])
ON UPDATE NO ACTION ON DELETE CASCADE;
GO
ALTER TABLE [ChiTietTGH]
ADD FOREIGN KEY([MaLop]) REFERENCES [LopHocPhan]([MaLop])
ON UPDATE NO ACTION ON DELETE CASCADE;
GO

CREATE TRIGGER TRG_NgayHoc
ON NgayHoc
INSTEAD OF INSERT
AS
BEGIN
	DECLARE @NewID INT, @MaNH NVARCHAR(10);

	INSERT INTO NgayHoc(MaNH, Ngay, Thu)
	SELECT
		'NH' + RIGHT('000' + CAST(NEXT VALUE FOR Seq_MaNH AS NVARCHAR(3)), 3),
		Ngay,
		Thu
	FROM inserted;
END;